name: CI
on: push

jobs:
  verify:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true

      - run: yarn install
      - run: make test
