name: Ruby
on: push

jobs:
  verify:
    name: Ruby
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
